/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NULL_H_RPCGEN
#define _NULL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NFS 100003
#define NFS_VERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define NFS_NULL 0
extern  void * nfs_null_3(void *, CLIENT *);
extern  void * nfs_null_3_svc(void *, struct svc_req *);
extern int nfs_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NFS_NULL 0
extern  void * nfs_null_3();
extern  void * nfs_null_3_svc();
extern int nfs_3_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NULL_H_RPCGEN */
