/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "program.h"

void *
nfsproc3_null_3_svc(void *argp, struct svc_req *rqstp)
{
	static char *result;

	/*
	 * insert server code here
	 */
	printf("-----null-----\n");

	return (void *)&result;
}

GETATTR3res *
nfsproc3_getattr_3_svc(GETATTR3args *argp, struct svc_req *rqstp)
{
	static GETATTR3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

SETATTR3res *
nfsproc3_setattr_3_svc(SETATTR3args *argp, struct svc_req *rqstp)
{
	static SETATTR3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

LOOKUP3res *
nfsproc3_lookup_3_svc(LOOKUP3args *argp, struct svc_req *rqstp)
{
	static LOOKUP3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

ACCESS3res *
nfsproc3_access_3_svc(ACCESS3args *argp, struct svc_req *rqstp)
{
	static ACCESS3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

READLINK3res *
nfsproc3_readlink_3_svc(READLINK3args *argp, struct svc_req *rqstp)
{
	static READLINK3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

READ3res *
nfsproc3_read_3_svc(READ3args *argp, struct svc_req *rqstp)
{
	static READ3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

WRITE3res *
nfsproc3_write_3_svc(WRITE3args *argp, struct svc_req *rqstp)
{
	static WRITE3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

CREATE3res *
nfsproc3_create_3_svc(CREATE3args *argp, struct svc_req *rqstp)
{
	static CREATE3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

MKDIR3res *
nfsproc3_mkdir_3_svc(MKDIR3args *argp, struct svc_req *rqstp)
{
	static MKDIR3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

SYMLINK3res *
nfsproc3_symlink_3_svc(SYMLINK3args *argp, struct svc_req *rqstp)
{
	static SYMLINK3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

MKNOD3res *
nfsproc3_mknod_3_svc(MKNOD3args *argp, struct svc_req *rqstp)
{
	static MKNOD3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

REMOVE3res *
nfsproc3_remove_3_svc(REMOVE3args *argp, struct svc_req *rqstp)
{
	static REMOVE3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

RMDIR3res *
nfsproc3_rmdir_3_svc(RMDIR3args *argp, struct svc_req *rqstp)
{
	static RMDIR3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

RENAME3res *
nfsproc3_rename_3_svc(RENAME3args *argp, struct svc_req *rqstp)
{
	static RENAME3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

LINK3res *
nfsproc3_link_3_svc(LINK3args *argp, struct svc_req *rqstp)
{
	static LINK3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

READDIR3res *
nfsproc3_readdir_3_svc(READDIR3args *argp, struct svc_req *rqstp)
{
	static READDIR3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

READDIRPLUS3res *
nfsproc3_readdirplus_3_svc(READDIRPLUS3args *argp, struct svc_req *rqstp)
{
	static READDIRPLUS3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

FSSTAT3res *
nfsproc3_fsstat_3_svc(FSSTAT3args *argp, struct svc_req *rqstp)
{
	static FSSTAT3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

FSINFO3res *
nfsproc3_fsinfo_3_svc(FSINFO3args *argp, struct svc_req *rqstp)
{
	static FSINFO3res result;

	/*
	 * insert server code here
	 */
	printf("-----fsinfo-----\n");
	printf("fsroot.data.data_len: %u\n", argp->fsroot.data.data_len);
	printf("fsroot.data.data_val: %s\n", argp->fsroot.data.data_val);
	post_op_attr obj_attributes = {FALSE};
	FSINFO3resfail resfail = {obj_attributes};
	result.status = NFS3ERR_BADTYPE;
	result.FSINFO3res_u.resfail = resfail;

	return &result;
}

PATHCONF3res *
nfsproc3_pathconf_3_svc(PATHCONF3args *argp, struct svc_req *rqstp)
{
	static PATHCONF3res result;

	/*
	 * insert server code here
	 */

	return &result;
}

COMMIT3res *
nfsproc3_commit_3_svc(COMMIT3args *argp, struct svc_req *rqstp)
{
	static COMMIT3res result;

	/*
	 * insert server code here
	 */

	return &result;
}
