/* SPDX-License-Identifier: unknown license... */
/*
 * The content of this file is a mix of rpcgen-generated
 * and hand-edited program text.  It is not automatically
 * generated by, e.g., build processes.
 *
 * This file is under version control.
 */

#ifndef _NFS23_H_RPCGEN
#define	_NFS23_H_RPCGEN

//#include "gsh_rpc.h"
//#include "extended_types.h"
//#include "mount.h"
//#include "fsal_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#define NFS2_MAXDATA 8192
#define NFS2_MAXPATHLEN 1024
#define NFS2_MAXNAMLEN 255
#define NFS2_COOKIESIZE 4
#define NFS2_FHSIZE 32
#define NFS2_MNTPATHLEN 1024
#define NFS2_MNTNAMLEN 255

#define NFS3_FHSIZE 64
#define NFS3_COOKIEVERFSIZE 8
#define NFS3_CREATEVERFSIZE 8
#define NFS3_WRITEVERFSIZE 8

#define NFS2_MAX_FILESIZE   (2147483647)	/* 0x7fffffff */

typedef char fhandle2[NFS2_FHSIZE];

struct fhstatus2 {
	u_int status;
	union {
		fhandle2 directory;
	} fhstatus2_u;
};
typedef struct fhstatus2 fhstatus2;

typedef char *nfspath2;

typedef char *filename2;

typedef struct {
	u_int nfsdata2_len;
	char *nfsdata2_val;
} nfsdata2;

enum nfsstat2 {
	NFS_OK = 0,
	NFSERR_PERM = 1,
	NFSERR_NOENT = 2,
	NFSERR_IO = 5,
	NFSERR_NXIO = 6,
	NFSERR_ACCES = 13,
	NFSERR_EXIST = 17,
	NFSERR_NODEV = 19,
	NFSERR_NOTDIR = 20,
	NFSERR_ISDIR = 21,
	NFSERR_FBIG = 27,
	NFSERR_NOSPC = 28,
	NFSERR_ROFS = 30,
	NFSERR_NAMETOOLONG = 63,
	NFSERR_NOTEMPTY = 66,
	NFSERR_DQUOT = 69,
	NFSERR_STALE = 70,
	NFSERR_WFLUSH = 99
};

enum nfsstat3 {
	NFS3_OK = 0,
	NFS3ERR_PERM = 1,
	NFS3ERR_NOENT = 2,
	NFS3ERR_IO = 5,
	NFS3ERR_NXIO = 6,
	NFS3ERR_ACCES = 13,
	NFS3ERR_EXIST = 17,
	NFS3ERR_XDEV = 18,
	NFS3ERR_NODEV = 19,
	NFS3ERR_NOTDIR = 20,
	NFS3ERR_ISDIR = 21,
	NFS3ERR_INVAL = 22,
	NFS3ERR_FBIG = 27,
	NFS3ERR_NOSPC = 28,
	NFS3ERR_ROFS = 30,
	NFS3ERR_MLINK = 31,
	NFS3ERR_NAMETOOLONG = 63,
	NFS3ERR_NOTEMPTY = 66,
	NFS3ERR_DQUOT = 69,
	NFS3ERR_STALE = 70,
	NFS3ERR_REMOTE = 71,
	NFS3ERR_BADHANDLE = 10001,
	NFS3ERR_NOT_SYNC = 10002,
	NFS3ERR_BAD_COOKIE = 10003,
	NFS3ERR_NOTSUPP = 10004,
	NFS3ERR_TOOSMALL = 10005,
	NFS3ERR_SERVERFAULT = 10006,
	NFS3ERR_BADTYPE = 10007,
	NFS3ERR_JUKEBOX = 10008
};
typedef enum nfsstat3 nfsstat3;

enum ftype3 {
	NF3REG = 1,
	NF3DIR = 2,
	NF3BLK = 3,
	NF3CHR = 4,
	NF3LNK = 5,
	NF3SOCK = 6,
	NF3FIFO = 7
};
typedef enum ftype3 ftype3;

#define	NFS_PROGRAM	100003
#define	NFS_V2	2
#define	NFSPROC_NULL	0
#define	NFSPROC_GETATTR	1
#define	NFSPROC_SETATTR	2
#define	NFSPROC_ROOT	3
#define	NFSPROC_LOOKUP	4
#define	NFSPROC_READLINK	5
#define	NFSPROC_READ	6
#define	NFSPROC_WRITECACHE	7
#define	NFSPROC_WRITE	8
#define	NFSPROC_CREATE	9
#define	NFSPROC_REMOVE	10
#define	NFSPROC_RENAME	11
#define	NFSPROC_LINK	12
#define	NFSPROC_SYMLINK	13
#define	NFSPROC_MKDIR	14
#define	NFSPROC_RMDIR	15
#define	NFSPROC_READDIR	16
#define	NFSPROC_STATFS	17
#define	NFS_V3	3
#define	NFSPROC3_NULL	0
#define	NFSPROC3_GETATTR	1
#define	NFSPROC3_SETATTR	2
#define	NFSPROC3_LOOKUP	3
#define	NFSPROC3_ACCESS	4
#define	NFSPROC3_READLINK	5
#define	NFSPROC3_READ	6
#define	NFSPROC3_WRITE	7
#define	NFSPROC3_CREATE	8
#define	NFSPROC3_MKDIR	9
#define	NFSPROC3_SYMLINK	10
#define	NFSPROC3_MKNOD	11
#define	NFSPROC3_REMOVE	12
#define	NFSPROC3_RMDIR	13
#define	NFSPROC3_RENAME	14
#define	NFSPROC3_LINK	15
#define	NFSPROC3_READDIR	16
#define	NFSPROC3_READDIRPLUS	17
#define	NFSPROC3_FSSTAT	18
#define	NFSPROC3_FSINFO	19
#define	NFSPROC3_PATHCONF	20
#define	NFSPROC3_COMMIT	21

typedef char writeverf3[8];

#ifdef __cplusplus
}
#endif

#endif				/* !_NFS23_H_RPCGEN */
