/* SPDX-License-Identifier: unknown license... */
/*
 * The content of this file is a mix of rpcgen-generated
 * and hand-edited program text.  It is not automatically
 * generated by, e.g., build processes.
 *
 * This file is under version control.
 */

#ifndef NFS_NFS_BASE_H
#define	NFS_NFS_BASE_H

extern "C" {
#include "rpc/types.h"
}

#include "file/file_base.h"

#define	NFS_PROGRAM	100003

#define	NFS_V4	4

#endif				/* !NFS_NFS_BASE_H */
